### ISSUE TITLE
Solving Dependency issues

### ISSUE THREAD

**Issue by arefmalek** [habla-liaa/ser-with-w2v2#17]
Hello! I love the project and especially your results, I am trying to replicate results locally and having some issues:

I tried installation and although I had the same issue as [here](https://github.com/habla-liaa/ser-with-w2v2/issues/14), I was able to clear it on ubuntu. However, the actual dependency list itself is troublesome. 

For reference, I installed the requirements on this repository (BTW, the dependency formatted as `git~..github.com..` does not work, I installed stuff manually instead), then I went and installed everything on [paips](https://github.com/mrpep/paips) and afterwards from [kahnfigh](https://github.com/mrpep/kahnfigh). Even with this, I still have issues with dependencies as such:

```
+ export LC_NUMERIC=en_US.UTF-8
+ LC_NUMERIC=en_US.UTF-8
+ export PYTHONHASHSEED=1234
+ PYTHONHASHSEED=1234
+ SEED=1
+ OUTPUT_PATH=./outputs/output
+ seed_mod=global/seed=1
+ errors=1
+ (( 1!=0 ))
+ paiprun configs/main/os-baseline.yaml --output_path ./outputs/output/none-egemaps/1 --mods global/seed=1
Warning: Cannot resolve tags ['normalization_axis', 'normalization_axis', 'normalization_axis', 'opensmile_exclude_features', 'opensmile_features', 'normalization_axis', 'normalization_axis', 'normalization_axis', 'opensmile_exclude_features', 'opensmile_features']
Traceback (most recent call last):
  File "/home/csuser/.local/lib/python3.10/site-packages/paips/utils/modiuls.py", line 34, in get_modules
    module = module_from_file(Path(module_path).stem,module_path)
  File "/home/csuser/.local/lib/python3.10/site-packages/paips/utils/modiuls.py", line 8, in module_from_file
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/csuser/.local/lib/python3.10/site-packages/paips/utils/modiuls.py", line 37, in get_modules
    module = module_from_folder(module_path)    
  File "/home/csuser/.local/lib/python3.10/site-packages/paips/utils/modiuls.py", line 22, in module_from_folder
    module = importlib.import_module(module_path.stem)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/csuser/Desktop/ser-with-w2v2/tasks/__init__.py", line 2, in <module>
    from .audio_dataset_from_directory import *
  File "/home/csuser/Desktop/ser-with-w2v2/tasks/audio_dataset_from_directory.py", line 4, in <module>
    from pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'pymediainfo'
```

There are more, but just replicating the results is turning out to be a lot more difficult than I initially anticipated. Are there any solutions you have to help me easily get set up? Ideally something as simple as pip install requirement, run this torch script, and see results, but let me know. Thanks!

**Comment by mrpep** [comment]
Sorry for the late reply, I updated requirements and was able to rerun the experiments
