### ISSUE TITLE
 'tf_utils' from 'tensorflow.keras.utils' 

### ISSUE THREAD

**Issue by Chase0310** [habla-liaa/ser-with-w2v2#18]
+ OUTPUT_PATH=./output/
+ ./run_paper_experiments.sh 0123 ./output/
+ export LC_NUMERIC=en_US.UTF-8
+ LC_NUMERIC=en_US.UTF-8
+ export PYTHONHASHSEED=1234
+ PYTHONHASHSEED=1234
+ SEED=0123
+ OUTPUT_PATH=./output/
+ seed_mod=global/seed=0123
+ errors=1
+ (( 1!=0 ))
+ paiprun configs/main/os-baseline.yaml --output_path ./output//none-egemaps/0123 --mods global/seed=0123
Warning: Cannot resolve tags ['normalization_axis', 'normalization_axis', 'normalization_axis', 'opensmile_exclude_features', 'opensmile_features', 'normalization_axis', 'normalization_axis', 'normalization_axis', 'opensmile_exclude_features', 'opensmile_features']
2023-09-22 19:59:21.988380: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.11.0 and strictly below 2.14.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.4.1 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  warnings.warn(
Traceback (most recent call last):
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/paips/utils/modiuls.py", line 34, in get_modules
    module = module_from_file(Path(module_path).stem,module_path)
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/paips/utils/modiuls.py", line 8, in module_from_file
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 553, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/paips/utils/modiuls.py", line 37, in get_modules
    module = module_from_folder(module_path)    
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/paips/utils/modiuls.py", line 22, in module_from_folder
    module = importlib.import_module(module_path.stem)
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yyccll/pyPro/ser-with-w2v2/tasks/__init__.py", line 8, in <module>
    from .dienen_tasks import *
  File "/home/yyccll/pyPro/ser-with-w2v2/tasks/dienen_tasks.py", line 6, in <module>
    from dienen import Model
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/dienen/__init__.py", line 3, in <module>
    from .core.model import Model
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/dienen/core/__init__.py", line 1, in <module>
    from .architecture import Architecture
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/dienen/core/architecture.py", line 2, in <module>
    from .layer import Layer
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/dienen/core/layer.py", line 4, in <module>
    import tensorflow_addons as tfa
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/__init__.py", line 24, in <module>
    from tensorflow_addons import callbacks
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/callbacks/__init__.py", line 17, in <module>
    from tensorflow_addons.callbacks.average_model_checkpoint import AverageModelCheckpoint
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/callbacks/average_model_checkpoint.py", line 18, in <module>
    from tensorflow_addons.optimizers.average_wrapper import AveragedOptimizerWrapper
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/optimizers/__init__.py", line 30, in <module>
    from tensorflow_addons.optimizers.discriminative_layer_training import (
  File "/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow_addons/optimizers/discriminative_layer_training.py", line 34, in <module>
    from tensorflow.keras.utils import tf_utils
ImportError: cannot import name 'tf_utils' from 'tensorflow.keras.utils' (/home/yyccll/.conda/envs/TF8/lib/python3.8/site-packages/tensorflow/keras/utils/__init__.py)

  I have installed all the packages you recommended, while running under TF2.4.1 and keras2.4.3 reported errors, I made sure that my keras can run through other samples.

**Comment by Chase0310** [comment]
Oh, I know what's wrong! By default, pip tensorflow2.4.1 will get a later version of tensorflow-addons, you should change it manually!

**Comment by mrpep** [comment]
Sorry for the very late reply. I updated requirements with the right version.
