### ISSUE TITLE
 Can you tell me how to solve it？

### ISSUE THREAD

**Issue by baozixifan** [habla-liaa/ser-with-w2v2#2]
When I run this code, I get the following error message. Can you tell me how to solve it？

Traceback (most recent call last):
  File "/home/ljj/anaconda3/envs/SER/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'emotion'

**Comment by mrpep** [comment]
Hi!, can you provide more details on how you ran the code? Also please provide the full logs so I can help you.
Did you execute ./run_seeds.sh and place the datasets with the folder structure shown in the readme?

**Comment by mrpep** [comment]
I faced the same issue when recreating this repository from scratch in a new environment. It was because libmediainfo-dev was not installed in the system. I updated the README.
