### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'annotations'

### ISSUE THREAD

**Issue by jiminbot20** [habla-liaa/ser-with-w2v2#3]
Hi, first of all thank you for your code

https://github.com/habla-liaa/ser-with-w2v2/blob/f3983fa0caaa122b69e549f1e558d17538001c81/tasks/IEMOCAP_reader.py#L137

**error appears at above line, when running _./run_seeds.sh <output_path>_**

Traceback (most recent call last):
  File "/opt/conda/bin/paiprun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/paips/run_paips.py", line 50, in main
    main_task.run()
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 459, in run
    out_dict = self.__serial_run(run_async=run_async)
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 346, in __serial_run
    outs = self.process()
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 654, in process
    out_dict = task.run()
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 459, in run
    out_dict = self.__serial_run(run_async=run_async)
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 346, in __serial_run
    outs = self.process()
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 654, in process
    out_dict = task.run()
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 459, in run
    out_dict = self.__serial_run(run_async=run_async)
  File "/opt/conda/lib/python3.8/site-packages/paips/core.py", line 346, in __serial_run
    outs = self.process()
  File "/home/emotion/w2v/tasks/IEMOCAP_reader.py", line 137, in process
    df_data['annotations_entropy'] = df_data.annotations.map(lambda x: list2entropy(x[:3]))
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'annotations'

**Could you please help solving this problem?**

**Comment by jiminbot20** [comment]
This was my mistake. my database in IEMOCAP named _sentence_ , it supposed to be _sentences_
